{
 "title": "Rocket Pool Dashboard v1.3.0",
 "description": "This is the standard dashboard for Rocket Pool node operators.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DS_PROMETHEUS" },
   { "name": "service", "label": "service" }
  ]
 },
 "panels": [
  {
   "title": "Rocket Pool Network Stats (Updates Every 5 Minutes)",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Beacon Chain Rewards (Updates Every 5 Minutes)",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 13, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total ETH Locked",
   "type": "stat",
   "description": "The total amount of ETH locked on the Rocket Pool network, including staked RPL (but not including Beacon Chain rewards).",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_demand_deposit_pool_balance{app=\"${service}\"} + rocketpool_demand_total_minipool_capacity{app=\"${service}\"} + rocketpool_supply_active_minipools{app=\"${service}\"} * 32 + rocketpool_rpl_total_value_staked{app=\"${service}\"} * rocketpool_rpl_rpl_price{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Total RPL Staked",
   "type": "stat",
   "description": "The total amount of RPL staked across all node operators in the Rocket Pool network.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_rpl_total_value_staked{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Total Effective RPL Staked",
   "type": "stat",
   "description": "The total *effective* RPL stake across all node operators on the Rocket Pool network. This accounts for the 150% collateral cap per minipool. If this number is lower than the Total RPL Staked, then some node operators have gone above 150%.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_rpl_total_effective_staked{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Smoothing Pool Balance",
   "type": "stat",
   "description": "The current balance of the Smoothing Pool. This is what will get distributed to each node operator opted into the Smoothing Pool at the end of each rewards interval.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_smoothing_pool_eth_balance{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Beacon Balance",
   "type": "stat",
   "description": "The total ETH balance of all of your Rocket Pool validators on the Beacon Chain. This includes both ETH belonging to you and ETH belonging to the pool stakers you used to make your minipools.",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_beacon_balance{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Minipool Balance (EL)",
   "type": "stat",
   "description": "This is how much ETH is currently available for distribution in each of your minipool contracts (on the execution layer). Note that if any of them have a refund, this shows the total balance **minus** that refund amount - in other words, it shows whatever's left over after your refund.",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_minipool_balance{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Other ETH Rewards",
   "type": "stat",
   "description": "A collection of other ETH rewards you can claim (or have claimed).\n\n- **Unclaimed ETH (SP)**: ETH you've earned from the Smoothing Pool that you haven't claimed yet.\n- **Claimed ETH (SP)**: ETH from the Smoothing Pool you've already claimed in the past.\n- **Total Refund**: ETH that belongs to you from special operations like bond reduction or solo staker migration. When you claim this, it goes directly to you - it isn't split with the pool stakers.",
   "gridPos": { "h": 9, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_unclaimed_eth_rewards{app=\"${service}\"}",
     "legendFormat": "Unclaimed ETH (SP)"
    },
    {
     "expr": "rocketpool_node_claimed_eth_rewards{app=\"${service}\"}",
     "legendFormat": "Claimed ETH (SP)"
    },
    {
     "expr": "rocketpool_node_refund_balance{app=\"${service}\"}",
     "legendFormat": "Total Refund"
    }
   ]
  },
  {
   "title": "Your Beacon Chain Share",
   "type": "stat",
   "description": "This is how much ETH you will receive if you exit all of your validators on the Beacon Chain; it's your share of the total balance for each Rocket Pool minipool.",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_beacon_share{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Your Minipool (EL) Share",
   "type": "stat",
   "description": "The total amount of ETH that belongs to you across the EL balances of all of your minipool contracts (minus any refunds you may have waiting).",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_minipool_share{app=\"${service}\"}",
     "legendFormat": "annualized daily return"
    }
   ]
  },
  {
   "title": "rETH Price (ETH / rETH)",
   "type": "stat",
   "description": "The amount of ETH that 1 rETH is worth.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_performance_eth_reth_exchange_rate{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "RPL Price (ETH / RPL)",
   "type": "stat",
   "description": "The amount of ETH that 1 RPL is worth, as reported by the Oracle DAO. This updates somewhat infrequently, so it's expected if it falls out of sync with other price watchers.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_rpl_rpl_price{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Staking Pool Balance",
   "type": "gauge",
   "description": "The amount of ETH currently in the staking pool, waiting to be used by node operators to create new minipools.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_demand_deposit_pool_balance{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Minipools in Queue",
   "type": "stat",
   "description": "The number of minipools that are currently in the queue, waiting for ETH to be assigned to them from the staking pool.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_demand_queue_length{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "stat",
   "description": "The total number of nodes that have registered on the Rocket Pool network.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_supply_node_count{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Minipools by Status",
   "type": "piechart",
   "description": "A breakdown of the counts of each minipool on the Rocket Pool network by status:\n\n- **Initialized**: waiting for a deposit still\n- **Prelaunch:** deposits are done, waiting to be staked by the node operator's `rocketpool_node` container \n- **Staking:** deposited, validator created, and active (or pending) on the Beacon Chain\n- **Dissolved:** staking failed, funds returned to the node operator and staking pool\n- **Withdrawable:** exited from the Beacon Chain, waiting for rewards to be withdrawn to the minipool\n- **Finalized:** exited, withdrawn from, and essentially closed (inactive)",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_supply_minipool_count{app=\"${service}\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "RPL Rewards (Updates Every 5 Minutes)",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 13, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Staking Pool ETH Used",
   "type": "gauge",
   "description": "The relative amount of ETH that was deposited into the staking pool by rETH stakers, which was then used by node operators to create new minipools with validators on the Beacon Chain. The closer this number is to 100%, the more efficiently the Rocket Pool network is operating and the faster rETH's price grows.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_performance_eth_utilization_rate{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "ETH Capacity of Queue",
   "type": "stat",
   "description": "The total amount of ETH needed to be added to the staking pool in order to clear the minipool queue completely.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_demand_total_minipool_capacity{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Next RPL Rewards Checkpoint",
   "type": "stat",
   "description": "The time of the next RPL rewards checkpoint. If you have an effective RPL stake greater than zero, you should receive rewards here (unless it's your first checkpoint, in which case you'll need to wait a bit longer).",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_rpl_checkpoint_time{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Next RPL Rewards Checkpoint",
   "type": "stat",
   "description": "This tracks how long you have until the next RPL rewards checkpoint.",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_rpl_checkpoint_time{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Active Minipools",
   "type": "stat",
   "description": "The total number of Rocket Pool minipools (validators) that are active (not exited and withdrawn from the Beacon Chain).",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_supply_active_minipools{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "RPL Staked",
   "type": "stat",
   "description": "This shows various levels of RPL stake you have:\n\n- **Total**: the total amount of RPL you have staked.\n- **Effective**: the amount of your staked RPL that is being put to use, accounting for the 10% borrowed minimum and 150% bonded maximum limits.\n- **Rewardable**: the effective amount of RPL that is eligible for earning RPL rewards at the end of each rewards period. This is based on the status of your validators on the Beacon Chain; validators that haven't been activated yet or validators that have been exited are not eligible for rewards.\n\n**Note**: this takes any *pending bond reductions* you may have into account.",
   "gridPos": { "h": 13, "w": 3, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "RPL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_total_staked_rpl{app=\"${service}\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "rocketpool_node_effective_staked_rpl{app=\"${service}\"}",
     "legendFormat": "Effective"
    },
    {
     "expr": "rocketpool_node_rewardable_staked_rpl{app=\"${service}\"}",
     "legendFormat": "Rewardable"
    }
   ]
  },
  {
   "title": "RPL Collateral",
   "type": "gauge",
   "description": "Your total staked RPL collateral levels. This shows your collateral relative to the amount of ETH you have *borrowed* from the staking pool to complete your validators, and the amount of ETH you have *bonded* with your own funds.\n\nIf you fall below 10% of the *borrowed* ETH, you won't be able to claim your rewards at the next checkpoint until you get back to 10%.\n\nIf you go over 150% of the *bonded* ETH, you'll only be rewarded for the first 150% of your stake.",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_borrowed_collateral_ratio{app=\"${service}\"}",
     "legendFormat": "Borrowed"
    },
    {
     "expr": "rocketpool_node_bonded_collateral_ratio{app=\"${service}\"}",
     "legendFormat": "Bonded"
    }
   ]
  },
  {
   "title": "Validator stats",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Your Minipools",
   "type": "stat",
   "description": "How many minipools you currently have running on your node.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_active_minipool_count{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Governance (Updates Every 6 Hours)",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Proposals",
   "type": "stat",
   "description": "The number of active proposals you or your delegate have voted on.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_snapshot_votes_active{app=\"${service}\"}",
     "legendFormat": "Voted"
    },
    {
     "expr": "rocketpool_snapshot_proposals_active - rocketpool_snapshot_votes_active",
     "legendFormat": "Missing votes"
    }
   ]
  },
  {
   "title": "Closed Proposals",
   "type": "stat",
   "description": "Shows the number of closed votes you or your delegate has voted or missed.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_snapshot_votes_closed{app=\"${service}\"}",
     "legendFormat": "Voted"
    },
    {
     "expr": "rocketpool_snapshot_proposals_closed{app=\"${service}\"} - rocketpool_snapshot_votes_closed{app=\"${service}\"}",
     "legendFormat": "Missed votes"
    }
   ]
  },
  {
   "title": "Node Voting Power",
   "type": "stat",
   "description": "The node voting power on Snapshot.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_snapshot_node_vp {app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Delegate Voting Power",
   "type": "stat",
   "description": "The voting power of the delegate you have chosen.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_snapshot_delegate_vp {app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Approx. Rewards from Next Checkpoint",
   "type": "stat",
   "description": "The approximate amount of RPL you'll receive at the next checkpoint, based on your current rewardable stake and how much RPL is staked on the entire network.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "RPL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_expected_rpl_rewards{app=\"${service}\"}"
    }
   ]
  },
  {
   "title": "RPL Rewards",
   "type": "stat",
   "description": "The amount of RPL you've claimed over the life of your node, and the amount you still have yet to claim.",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "RPL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_unclaimed_rewards{app=\"${service}\"}",
     "legendFormat": "Unclaimed"
    },
    {
     "expr": "rocketpool_node_cumulative_rpl_rewards{app=\"${service}\"}",
     "legendFormat": "Claimed"
    }
   ]
  },
  {
   "title": "Your RPL APR for the Next Checkpoint",
   "type": "stat",
   "description": "The approximate APR for your RPL stake, based on the rewards you will receive at the next checkpoint.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rocketpool_node_rpl_apr{app=\"${service}\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 13, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node Wallet Balances",
   "type": "table",
   "description": "The balances of your node wallet (only tracks Rocket Pool tokens). Keep an eye on how much ETH you have; if it falls too low, your node won't be able to pay for gas during automatic RPL reward claims or other transactions.",
   "gridPos": { "h": 6, "w": 9, "x": 13, "y": 29 },
   "targets": [
    {
     "expr": "rocketpool_node_balance{app=\"${service}\"}",
     "legendFormat": "{{Token}}"
    }
   ]
  }
 ]
}